version: '3.8'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo
    networks:
      - netflix-net

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    networks:
      - netflix-net

networks:
  netflix-net:
    driver: bridge
